# Generated by Django 4.1.7 on 2023-03-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
        migrations.AddField(
            model_name='image',
            name='owner',
            field=models.CharField(default='admin', max_length=20),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(default='name', max_length=30),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(default='test', max_length=20),
        ),
    ]
