# Generated by Django 4.1.7 on 2023-03-02 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_remove_image_image_remove_image_url_image_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
