# Generated by Django 4.1.7 on 2023-03-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_remove_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='hight',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='name', max_length=30),
        ),
        migrations.AddField(
            model_name='image',
            name='width',
            field=models.IntegerField(default=400),
        ),
    ]
