# Generated by Django 4.1.7 on 2023-03-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_rename_hight_image_height'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.RemoveField(
            model_name='image',
            name='height',
        ),
        migrations.RemoveField(
            model_name='image',
            name='width',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='files'),
        ),
    ]
