# Generated by Django 4.1.7 on 2023-03-05 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0010_image_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
    ]
